/**
 * Per-page accent themes.
 *
 * Every dashboard page carries its own accent color so users can tell at a
 * glance where they are. Classes are written out literally on purpose so
 * Tailwind's scanner generates them; never build them dynamically.
 */

const THEMES = {
  red: {
    name: "red",
    hex: "#ef4444",
    softHex: "#fee2e2",
    text: "text-red-600",
    textStrong: "text-red-700",
    textSoft: "text-red-500",
    bgSoft: "bg-red-50",
    bgSofter: "bg-red-50/60",
    bgSoftStrong: "bg-red-100",
    border: "border-red-200",
    borderSoft: "border-red-100",
    borderFaint: "border-red-50",
    chip: "bg-red-50 text-red-600",
    chipHover: "hover:bg-red-100",
    solid: "bg-red-600 dark:bg-red-400",
    solidHover: "hover:bg-red-700 dark:hover:bg-red-300",
    solidText: "text-white dark:text-red-950",
    hoverBgSoft: "hover:bg-red-50",
    hoverBorder: "hover:border-red-200 dark:hover:border-red-500",
    groupHoverText: "group-hover:text-red-600",
    gradient: "from-red-600 to-red-700 dark:from-red-300 dark:to-red-200",
    gradientHover: "hover:from-red-700 hover:to-red-800 dark:hover:from-red-200 dark:hover:to-red-100",
    gradientText: "text-white dark:text-red-950",
    heroGradient: "from-red-600 via-red-600 to-black dark:from-red-300 dark:via-red-300",
    heroBg:
      "border-red-100 bg-gradient-to-br from-red-50 via-white to-gray-50",
    heroBgDark: "dark:from-red-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-red-400/30",
    tableHeaderBg: "from-red-50/70",
    tableHeaderText: "text-red-500/70",
    rowHover: "hover:bg-red-50/30",
    focus: "focus:border-red-300 focus:ring-red-500/10",
    searchBg: "bg-red-50/35",
    searchHover: "hover:border-red-200 hover:bg-red-50/55",
  },

  rose: {
    name: "rose",
    hex: "#e11d48",
    softHex: "#fecdd3",
    text: "text-rose-600",
    textStrong: "text-rose-700",
    textSoft: "text-rose-500",
    bgSoft: "bg-rose-50",
    bgSofter: "bg-rose-50/60",
    bgSoftStrong: "bg-rose-100",
    border: "border-rose-200",
    borderSoft: "border-rose-100",
    borderFaint: "border-rose-50",
    chip: "bg-rose-50 text-rose-600",
    chipHover: "hover:bg-rose-100",
    solid: "bg-rose-600 dark:bg-rose-400",
    solidHover: "hover:bg-rose-700 dark:hover:bg-rose-300",
    solidText: "text-white dark:text-rose-950",
    hoverBgSoft: "hover:bg-rose-50",
    hoverBorder: "hover:border-rose-200 dark:hover:border-rose-500",
    groupHoverText: "group-hover:text-rose-600",
    gradient: "from-rose-600 to-rose-700 dark:from-rose-300 dark:to-rose-200",
    gradientHover: "hover:from-rose-700 hover:to-rose-800 dark:hover:from-rose-200 dark:hover:to-rose-100",
    gradientText: "text-white dark:text-rose-950",
    heroGradient: "from-rose-600 via-rose-600 to-black dark:from-rose-300 dark:via-rose-300",
    heroBg:
      "border-rose-100 bg-gradient-to-br from-rose-50 via-white to-gray-50",
    heroBgDark: "dark:from-rose-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-rose-400/30",
    tableHeaderBg: "from-rose-50/70",
    tableHeaderText: "text-rose-500/70",
    rowHover: "hover:bg-rose-50/30",
    focus: "focus:border-rose-300 focus:ring-rose-500/10",
    searchBg: "bg-rose-50/35",
    searchHover: "hover:border-rose-200 hover:bg-rose-50/55",
  },

  violet: {
    name: "violet",
    hex: "#7c3aed",
    softHex: "#ddd6fe",
    text: "text-violet-600",
    textStrong: "text-violet-700",
    textSoft: "text-violet-500",
    bgSoft: "bg-violet-50",
    bgSofter: "bg-violet-50/60",
    bgSoftStrong: "bg-violet-100",
    border: "border-violet-200",
    borderSoft: "border-violet-100",
    borderFaint: "border-violet-50",
    chip: "bg-violet-50 text-violet-600",
    chipHover: "hover:bg-violet-100",
    solid: "bg-violet-600 dark:bg-violet-400",
    solidHover: "hover:bg-violet-700 dark:hover:bg-violet-300",
    solidText: "text-white dark:text-violet-950",
    hoverBgSoft: "hover:bg-violet-50",
    hoverBorder: "hover:border-violet-200 dark:hover:border-violet-500",
    groupHoverText: "group-hover:text-violet-600",
    gradient: "from-violet-600 to-violet-700 dark:from-violet-300 dark:to-violet-200",
    gradientHover: "hover:from-violet-700 hover:to-violet-800 dark:hover:from-violet-200 dark:hover:to-violet-100",
    gradientText: "text-white dark:text-violet-950",
    heroGradient: "from-violet-600 via-violet-600 to-black dark:from-violet-300 dark:via-violet-300",
    heroBg:
      "border-violet-100 bg-gradient-to-br from-violet-50 via-white to-gray-50",
    heroBgDark: "dark:from-violet-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-violet-400/30",
    tableHeaderBg: "from-violet-50/70",
    tableHeaderText: "text-violet-500/70",
    rowHover: "hover:bg-violet-50/30",
    focus: "focus:border-violet-300 focus:ring-violet-500/10",
    searchBg: "bg-violet-50/35",
    searchHover: "hover:border-violet-200 hover:bg-violet-50/55",
  },

  indigo: {
    name: "indigo",
    hex: "#4f46e5",
    softHex: "#c7d2fe",
    text: "text-indigo-600",
    textStrong: "text-indigo-700",
    textSoft: "text-indigo-500",
    bgSoft: "bg-indigo-50",
    bgSofter: "bg-indigo-50/60",
    bgSoftStrong: "bg-indigo-100",
    border: "border-indigo-200",
    borderSoft: "border-indigo-100",
    borderFaint: "border-indigo-50",
    chip: "bg-indigo-50 text-indigo-600",
    chipHover: "hover:bg-indigo-100",
    solid: "bg-indigo-600 dark:bg-indigo-400",
    solidHover: "hover:bg-indigo-700 dark:hover:bg-indigo-300",
    solidText: "text-white dark:text-indigo-950",
    hoverBgSoft: "hover:bg-indigo-50",
    hoverBorder: "hover:border-indigo-200 dark:hover:border-indigo-500",
    groupHoverText: "group-hover:text-indigo-600",
    gradient: "from-indigo-600 to-indigo-700 dark:from-indigo-300 dark:to-indigo-200",
    gradientHover: "hover:from-indigo-700 hover:to-indigo-800 dark:hover:from-indigo-200 dark:hover:to-indigo-100",
    gradientText: "text-white dark:text-indigo-950",
    heroGradient: "from-indigo-600 via-indigo-600 to-black dark:from-indigo-300 dark:via-indigo-300",
    heroBg:
      "border-indigo-100 bg-gradient-to-br from-indigo-50 via-white to-gray-50",
    heroBgDark: "dark:from-indigo-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-indigo-400/30",
    tableHeaderBg: "from-indigo-50/70",
    tableHeaderText: "text-indigo-500/70",
    rowHover: "hover:bg-indigo-50/30",
    focus: "focus:border-indigo-300 focus:ring-indigo-500/10",
    searchBg: "bg-indigo-50/35",
    searchHover: "hover:border-indigo-200 hover:bg-indigo-50/55",
  },

  teal: {
    name: "teal",
    hex: "#0d9488",
    softHex: "#99f6e4",
    text: "text-teal-600",
    textStrong: "text-teal-700",
    textSoft: "text-teal-500",
    bgSoft: "bg-teal-50",
    bgSofter: "bg-teal-50/60",
    bgSoftStrong: "bg-teal-100",
    border: "border-teal-200",
    borderSoft: "border-teal-100",
    borderFaint: "border-teal-50",
    chip: "bg-teal-50 text-teal-600",
    chipHover: "hover:bg-teal-100",
    solid: "bg-teal-600 dark:bg-teal-400",
    solidHover: "hover:bg-teal-700 dark:hover:bg-teal-300",
    solidText: "text-white dark:text-teal-950",
    hoverBgSoft: "hover:bg-teal-50",
    hoverBorder: "hover:border-teal-200 dark:hover:border-teal-500",
    groupHoverText: "group-hover:text-teal-600",
    gradient: "from-teal-600 to-teal-700 dark:from-teal-300 dark:to-teal-200",
    gradientHover: "hover:from-teal-700 hover:to-teal-800 dark:hover:from-teal-200 dark:hover:to-teal-100",
    gradientText: "text-white dark:text-teal-950",
    heroGradient: "from-teal-600 via-teal-600 to-black dark:from-teal-300 dark:via-teal-300",
    heroBg:
      "border-teal-100 bg-gradient-to-br from-teal-50 via-white to-gray-50",
    heroBgDark: "dark:from-teal-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-teal-400/30",
    tableHeaderBg: "from-teal-50/70",
    tableHeaderText: "text-teal-500/70",
    rowHover: "hover:bg-teal-50/30",
    focus: "focus:border-teal-300 focus:ring-teal-500/10",
    searchBg: "bg-teal-50/35",
    searchHover: "hover:border-teal-200 hover:bg-teal-50/55",
  },

  amber: {
    name: "amber",
    hex: "#d97706",
    softHex: "#fde68a",
    text: "text-amber-600",
    textStrong: "text-amber-700",
    textSoft: "text-amber-500",
    bgSoft: "bg-amber-50",
    bgSofter: "bg-amber-50/60",
    bgSoftStrong: "bg-amber-100",
    border: "border-amber-200",
    borderSoft: "border-amber-100",
    borderFaint: "border-amber-50",
    chip: "bg-amber-50 text-amber-600",
    chipHover: "hover:bg-amber-100",
    solid: "bg-amber-600 dark:bg-amber-400",
    solidHover: "hover:bg-amber-700 dark:hover:bg-amber-300",
    solidText: "text-white dark:text-amber-950",
    hoverBgSoft: "hover:bg-amber-50",
    hoverBorder: "hover:border-amber-200 dark:hover:border-amber-500",
    groupHoverText: "group-hover:text-amber-600",
    gradient: "from-amber-600 to-amber-700 dark:from-amber-300 dark:to-amber-200",
    gradientHover: "hover:from-amber-700 hover:to-amber-800 dark:hover:from-amber-200 dark:hover:to-amber-100",
    gradientText: "text-white dark:text-amber-950",
    heroGradient: "from-amber-600 via-amber-600 to-black dark:from-amber-300 dark:via-amber-300",
    heroBg:
      "border-amber-100 bg-gradient-to-br from-amber-50 via-white to-gray-50",
    heroBgDark: "dark:from-amber-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-amber-400/30",
    tableHeaderBg: "from-amber-50/70",
    tableHeaderText: "text-amber-500/70",
    rowHover: "hover:bg-amber-50/30",
    focus: "focus:border-amber-300 focus:ring-amber-500/10",
    searchBg: "bg-amber-50/35",
    searchHover: "hover:border-amber-200 hover:bg-amber-50/55",
  },

  blue: {
    name: "blue",
    hex: "#2563eb",
    softHex: "#bfdbfe",
    text: "text-blue-600",
    textStrong: "text-blue-700",
    textSoft: "text-blue-500",
    bgSoft: "bg-blue-50",
    bgSofter: "bg-blue-50/60",
    bgSoftStrong: "bg-blue-100",
    border: "border-blue-200",
    borderSoft: "border-blue-100",
    borderFaint: "border-blue-50",
    chip: "bg-blue-50 text-blue-600",
    chipHover: "hover:bg-blue-100",
    solid: "bg-blue-600 dark:bg-blue-400",
    solidHover: "hover:bg-blue-700 dark:hover:bg-blue-300",
    solidText: "text-white dark:text-blue-950",
    hoverBgSoft: "hover:bg-blue-50",
    hoverBorder: "hover:border-blue-200 dark:hover:border-blue-500",
    groupHoverText: "group-hover:text-blue-600",
    gradient: "from-blue-600 to-blue-700 dark:from-blue-300 dark:to-blue-200",
    gradientHover: "hover:from-blue-700 hover:to-blue-800 dark:hover:from-blue-200 dark:hover:to-blue-100",
    gradientText: "text-white dark:text-blue-950",
    heroGradient: "from-blue-600 via-blue-600 to-black dark:from-blue-300 dark:via-blue-300",
    heroBg: "border-blue-100 bg-gradient-to-br from-blue-50 via-white to-gray-50",
    heroBgDark: "dark:from-blue-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-blue-400/30",
    tableHeaderBg: "from-blue-50/70",
    tableHeaderText: "text-blue-500/70",
    rowHover: "hover:bg-blue-50/30",
    focus: "focus:border-blue-300 focus:ring-blue-500/10",
    searchBg: "bg-blue-50/35",
    searchHover: "hover:border-blue-200 hover:bg-blue-50/55",
  },

  sky: {
    name: "sky",
    hex: "#0284c7",
    softHex: "#bae6fd",
    text: "text-sky-600",
    textStrong: "text-sky-700",
    textSoft: "text-sky-500",
    bgSoft: "bg-sky-50",
    bgSofter: "bg-sky-50/60",
    bgSoftStrong: "bg-sky-100",
    border: "border-sky-200",
    borderSoft: "border-sky-100",
    borderFaint: "border-sky-50",
    chip: "bg-sky-50 text-sky-600",
    chipHover: "hover:bg-sky-100",
    solid: "bg-sky-600 dark:bg-sky-400",
    solidHover: "hover:bg-sky-700 dark:hover:bg-sky-300",
    solidText: "text-white dark:text-sky-950",
    hoverBgSoft: "hover:bg-sky-50",
    hoverBorder: "hover:border-sky-200 dark:hover:border-sky-500",
    groupHoverText: "group-hover:text-sky-600",
    gradient: "from-sky-600 to-sky-700 dark:from-sky-300 dark:to-sky-200",
    gradientHover: "hover:from-sky-700 hover:to-sky-800 dark:hover:from-sky-200 dark:hover:to-sky-100",
    gradientText: "text-white dark:text-sky-950",
    heroGradient: "from-sky-600 via-sky-600 to-black dark:from-sky-300 dark:via-sky-300",
    heroBg: "border-sky-100 bg-gradient-to-br from-sky-50 via-white to-gray-50",
    heroBgDark: "dark:from-sky-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-sky-400/30",
    tableHeaderBg: "from-sky-50/70",
    tableHeaderText: "text-sky-500/70",
    rowHover: "hover:bg-sky-50/30",
    focus: "focus:border-sky-300 focus:ring-sky-500/10",
    searchBg: "bg-sky-50/35",
    searchHover: "hover:border-sky-200 hover:bg-sky-50/55",
  },

  emerald: {
    name: "emerald",
    hex: "#059669",
    softHex: "#a7f3d0",
    text: "text-emerald-600",
    textStrong: "text-emerald-700",
    textSoft: "text-emerald-500",
    bgSoft: "bg-emerald-50",
    bgSofter: "bg-emerald-50/60",
    bgSoftStrong: "bg-emerald-100",
    border: "border-emerald-200",
    borderSoft: "border-emerald-100",
    borderFaint: "border-emerald-50",
    chip: "bg-emerald-50 text-emerald-600",
    chipHover: "hover:bg-emerald-100",
    solid: "bg-emerald-600 dark:bg-emerald-400",
    solidHover: "hover:bg-emerald-700 dark:hover:bg-emerald-300",
    solidText: "text-white dark:text-emerald-950",
    hoverBgSoft: "hover:bg-emerald-50",
    hoverBorder: "hover:border-emerald-200 dark:hover:border-emerald-500",
    groupHoverText: "group-hover:text-emerald-600",
    gradient: "from-emerald-600 to-emerald-700 dark:from-emerald-300 dark:to-emerald-200",
    gradientHover: "hover:from-emerald-700 hover:to-emerald-800 dark:hover:from-emerald-200 dark:hover:to-emerald-100",
    gradientText: "text-white dark:text-emerald-950",
    heroGradient: "from-emerald-600 via-emerald-600 to-black dark:from-emerald-300 dark:via-emerald-300",
    heroBg:
      "border-emerald-100 bg-gradient-to-br from-emerald-50 via-white to-gray-50",
    heroBgDark: "dark:from-emerald-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-emerald-400/30",
    tableHeaderBg: "from-emerald-50/70",
    tableHeaderText: "text-emerald-500/70",
    rowHover: "hover:bg-emerald-50/30",
    focus: "focus:border-emerald-300 focus:ring-emerald-500/10",
    searchBg: "bg-emerald-50/35",
    searchHover: "hover:border-emerald-200 hover:bg-emerald-50/55",
  },

  orange: {
    name: "orange",
    hex: "#ea580c",
    softHex: "#fed7aa",
    text: "text-orange-600",
    textStrong: "text-orange-700",
    textSoft: "text-orange-500",
    bgSoft: "bg-orange-50",
    bgSofter: "bg-orange-50/60",
    bgSoftStrong: "bg-orange-100",
    border: "border-orange-200",
    borderSoft: "border-orange-100",
    borderFaint: "border-orange-50",
    chip: "bg-orange-50 text-orange-600",
    chipHover: "hover:bg-orange-100",
    solid: "bg-orange-600 dark:bg-orange-400",
    solidHover: "hover:bg-orange-700 dark:hover:bg-orange-300",
    solidText: "text-white dark:text-orange-950",
    hoverBgSoft: "hover:bg-orange-50",
    hoverBorder: "hover:border-orange-200 dark:hover:border-orange-500",
    groupHoverText: "group-hover:text-orange-600",
    gradient: "from-orange-600 to-orange-700 dark:from-orange-300 dark:to-orange-200",
    gradientHover: "hover:from-orange-700 hover:to-orange-800 dark:hover:from-orange-200 dark:hover:to-orange-100",
    gradientText: "text-white dark:text-orange-950",
    heroGradient: "from-orange-600 via-orange-600 to-black dark:from-orange-300 dark:via-orange-300",
    heroBg:
      "border-orange-100 bg-gradient-to-br from-orange-50 via-white to-gray-50",
    heroBgDark: "dark:from-orange-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-orange-400/30",
    tableHeaderBg: "from-orange-50/70",
    tableHeaderText: "text-orange-500/70",
    rowHover: "hover:bg-orange-50/30",
    focus: "focus:border-orange-300 focus:ring-orange-500/10",
    searchBg: "bg-orange-50/35",
    searchHover: "hover:border-orange-200 hover:bg-orange-50/55",
  },

  fuchsia: {
    name: "fuchsia",
    hex: "#c026d3",
    softHex: "#f5d0fe",
    text: "text-fuchsia-600",
    textStrong: "text-fuchsia-700",
    textSoft: "text-fuchsia-500",
    bgSoft: "bg-fuchsia-50",
    bgSofter: "bg-fuchsia-50/60",
    bgSoftStrong: "bg-fuchsia-100",
    border: "border-fuchsia-200",
    borderSoft: "border-fuchsia-100",
    borderFaint: "border-fuchsia-50",
    chip: "bg-fuchsia-50 text-fuchsia-600",
    chipHover: "hover:bg-fuchsia-100",
    solid: "bg-fuchsia-600 dark:bg-fuchsia-400",
    solidHover: "hover:bg-fuchsia-700 dark:hover:bg-fuchsia-300",
    solidText: "text-white dark:text-fuchsia-950",
    hoverBgSoft: "hover:bg-fuchsia-50",
    hoverBorder: "hover:border-fuchsia-200 dark:hover:border-fuchsia-500",
    groupHoverText: "group-hover:text-fuchsia-600",
    gradient: "from-fuchsia-600 to-fuchsia-700 dark:from-fuchsia-300 dark:to-fuchsia-200",
    gradientHover: "hover:from-fuchsia-700 hover:to-fuchsia-800 dark:hover:from-fuchsia-200 dark:hover:to-fuchsia-100",
    gradientText: "text-white dark:text-fuchsia-950",
    heroGradient: "from-fuchsia-600 via-fuchsia-600 to-black dark:from-fuchsia-300 dark:via-fuchsia-300",
    heroBg:
      "border-fuchsia-100 bg-gradient-to-br from-fuchsia-50 via-white to-gray-50",
    heroBgDark: "dark:from-fuchsia-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-fuchsia-400/30",
    tableHeaderBg: "from-fuchsia-50/70",
    tableHeaderText: "text-fuchsia-500/70",
    rowHover: "hover:bg-fuchsia-50/30",
    focus: "focus:border-fuchsia-300 focus:ring-fuchsia-500/10",
    searchBg: "bg-fuchsia-50/35",
    searchHover: "hover:border-fuchsia-200 hover:bg-fuchsia-50/55",
  },

  slate: {
    name: "slate",
    hex: "#475569",
    softHex: "#cbd5e1",
    text: "text-slate-600",
    textStrong: "text-slate-700",
    textSoft: "text-slate-500",
    bgSoft: "bg-slate-50",
    bgSofter: "bg-slate-50/60",
    bgSoftStrong: "bg-slate-100",
    border: "border-slate-200",
    borderSoft: "border-slate-100",
    borderFaint: "border-slate-50",
    chip: "bg-slate-50 text-slate-600",
    chipHover: "hover:bg-slate-100",
    solid: "bg-slate-600 dark:bg-slate-400",
    solidHover: "hover:bg-slate-700 dark:hover:bg-slate-300",
    solidText: "text-white dark:text-slate-950",
    hoverBgSoft: "hover:bg-slate-50",
    hoverBorder: "hover:border-slate-200 dark:hover:border-slate-500",
    groupHoverText: "group-hover:text-slate-600",
    gradient: "from-slate-600 to-slate-700 dark:from-slate-300 dark:to-slate-200",
    gradientHover: "hover:from-slate-700 hover:to-slate-800 dark:hover:from-slate-200 dark:hover:to-slate-100",
    gradientText: "text-white dark:text-slate-950",
    heroGradient: "from-slate-600 via-slate-600 to-black dark:from-slate-300 dark:via-slate-300",
    heroBg:
      "border-slate-100 bg-gradient-to-br from-slate-50 via-white to-gray-50",
    heroBgDark: "dark:from-slate-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-slate-400/30",
    tableHeaderBg: "from-slate-50/70",
    tableHeaderText: "text-slate-500/70",
    rowHover: "hover:bg-slate-50/30",
    focus: "focus:border-slate-300 focus:ring-slate-500/10",
    searchBg: "bg-slate-50/35",
    searchHover: "hover:border-slate-200 hover:bg-slate-50/55",
  },

  ink: {
    name: "ink",
    hex: "#111827",
    softHex: "#d1d5db",
    text: "text-gray-700",
    textStrong: "text-gray-900",
    textSoft: "text-gray-500",
    bgSoft: "bg-gray-100",
    bgSofter: "bg-gray-50/60",
    bgSoftStrong: "bg-gray-200",
    border: "border-gray-300",
    borderSoft: "border-gray-200",
    borderFaint: "border-gray-100",
    chip: "bg-gray-100 text-gray-700",
    chipHover: "hover:bg-gray-200",
    solid: "bg-gray-800 dark:bg-gray-200",
    solidHover: "hover:bg-gray-900 dark:hover:bg-gray-100",
    solidText: "text-white dark:text-gray-900",
    hoverBgSoft: "hover:bg-gray-50",
    hoverBorder: "hover:border-gray-300 dark:hover:border-gray-500",
    groupHoverText: "group-hover:text-gray-700",
    gradient: "from-gray-700 to-gray-900 dark:from-gray-300 dark:to-gray-100",
    gradientHover: "hover:from-gray-800 hover:to-black dark:hover:from-gray-200 dark:hover:to-gray-50",
    gradientText: "text-white dark:text-gray-900",
    heroGradient: "from-gray-700 via-gray-800 to-black dark:from-gray-300 dark:via-gray-200",
    heroBg:
      "border-gray-200 bg-gradient-to-br from-gray-50 via-white to-gray-50",
    heroBgDark:
      "dark:from-gray-100/50 dark:via-gray-100 dark:to-gray-50 dark:border-gray-400/30",
    tableHeaderBg: "from-gray-50/70",
    tableHeaderText: "text-gray-500/70",
    rowHover: "hover:bg-gray-50/30",
    focus: "focus:border-gray-400 focus:ring-gray-500/10",
    searchBg: "bg-gray-50/35",
    searchHover: "hover:border-gray-200 hover:bg-gray-50/55",
  },
};

export const PAGE_THEMES = THEMES;

/* =========================================================
   Route → theme mapping
========================================================= */

const ROUTE_THEMES = [
  { match: "/dashboard/notifications", theme: "red" },
  { match: "/dashboard/team", theme: "red" },
  { match: "/dashboard/portfolio", theme: "emerald" },
  { match: "/dashboard/categories", theme: "emerald" },
  { match: "/dashboard/teachers", theme: "emerald" },
  { match: "/dashboard/services", theme: "emerald" },
  { match: "/dashboard/pricing", theme: "emerald" },
  { match: "/dashboard/settings", theme: "emerald" },
  { match: "/dashboard/user", theme: "emerald" },
  { match: "/dashboard", theme: "red" },
];

export function getPageTheme(pathname = "/dashboard") {
  const match = ROUTE_THEMES.find(
    (entry) =>
      pathname === entry.match || pathname.startsWith(entry.match + "/"),
  );

  return THEMES[match?.theme] || THEMES.red;
}

const THEME_ALIASES = {
  primary: "red",
  danger: "red",
  success: "emerald",
  warning: "amber",
};

export function getThemeByName(name) {
  if (typeof name !== "string") return THEMES.red;

  const resolved = THEME_ALIASES[name] || name;

  return THEMES[resolved] || THEMES.red;
}
