import {
  FolderKanban,
  Rocket,
  Palette,
  Code2,
  Globe,
  Smartphone,
  ShoppingBag,
  Briefcase,
  Megaphone,
  PenTool,
  BarChart3,
  Camera,
  Gamepad2,
  GraduationCap,
  Heart,
  Star,
  Shield,
  Zap,
  Flag,
  Gift,
  Coffee,
  BookOpen,
  Building2,
  Plane,
} from "lucide-react";

export const PROJECT_ICONS = [
  { name: "folder", label: "مجلد", Icon: FolderKanban },
  { name: "rocket", label: "انطلاق", Icon: Rocket },
  { name: "palette", label: "تصميم", Icon: Palette },
  { name: "code", label: "برمجة", Icon: Code2 },
  { name: "globe", label: "ويب", Icon: Globe },
  { name: "smartphone", label: "جوال", Icon: Smartphone },
  { name: "bag", label: "متجر", Icon: ShoppingBag },
  { name: "briefcase", label: "أعمال", Icon: Briefcase },
  { name: "megaphone", label: "تسويق", Icon: Megaphone },
  { name: "pen", label: "كتابة", Icon: PenTool },
  { name: "chart", label: "تحليل", Icon: BarChart3 },
  { name: "camera", label: "محتوى", Icon: Camera },
  { name: "game", label: "ألعاب", Icon: Gamepad2 },
  { name: "study", label: "تعليم", Icon: GraduationCap },
  { name: "heart", label: "رعاية", Icon: Heart },
  { name: "star", label: "مميز", Icon: Star },
  { name: "shield", label: "أمان", Icon: Shield },
  { name: "zap", label: "سريع", Icon: Zap },
  { name: "flag", label: "هدف", Icon: Flag },
  { name: "gift", label: "هدية", Icon: Gift },
  { name: "coffee", label: "اجتماع", Icon: Coffee },
  { name: "book", label: "توثيق", Icon: BookOpen },
  { name: "building", label: "شركة", Icon: Building2 },
  { name: "plane", label: "سفر", Icon: Plane },
];

export function getProjectIcon(iconName = "folder") {
  return PROJECT_ICONS.find((item) => item.name === iconName)?.Icon || FolderKanban;
}
